const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const CHANGE_TEXT = 'CHANGE_TEXT';
const FILTER_ITEM = 'FILTER_ITEM';

export {
  ADD_ITEM,
  DELETE_ITEM,
  CHANGE_TEXT,
  FILTER_ITEM
}
