const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const CHANGE_TEXT = 'CHANGE_TEXT';
const FILTER_ITEM = 'FILTER_ITEM';
const REQUEST_LIST = 'REQUEST_LIST';
const RECEIVE_LIST = 'RECEIVE_LIST';

export {
  ADD_ITEM,
  DELETE_ITEM,
  CHANGE_TEXT,
  FILTER_ITEM,
  REQUEST_LIST,
  RECEIVE_LIST
}
